#pragma once
#include"Icons.h"

class Icon_BlackSister : public Icons
{
public:
	void Initialize()
	{

		string pic_temp[8] = {
			"  ╴▃▄▃▁  ‵,   ",
			"  ◢◤▇▆▅▄◣‘＼",
			"◢◤██. ██◥◣  ",
			"／▍＝█▍＼█▎＼‵",
			"＼▍◢█’ |◣▏‵  ",
			"    ▋‘一╯▏      ",
			"  ＼◥███◤      ",
			"      ▇▇▇        "
		};
		unsigned short background_color_temp[8][20] =
		{
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_GREEN,BG_GREEN,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_GREEN,BG_GREEN,	BG_GREEN,BG_GREEN,BG_GREEN,BG_GREEN,BG_GREEN,BG_GREEN,	BG_GREEN,BG_GREEN,BG_GREEN,BG_GREEN,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY, BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY, BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_LIGHTGREEN ,BG_LIGHTGREEN ,BG_LIGHTGREEN ,BG_LIGHTGREEN ,	BG_LIGHTGREEN ,BG_LIGHTGREEN,BG_GREEN ,BG_GREEN ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,	BG_LIGHTGREEN,BG_LIGHTGREEN,BG_LIGHTGREEN,BG_LIGHTGREEN,BG_LIGHTGREEN,BG_LIGHTGREEN,BG_LIGHTGREEN ,BG_LIGHTGREEN ,BG_WHITE ,BG_WHITE ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,	BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,	BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREEN,BG_LIGHTGREEN,	BG_LIGHTGREEN,BG_LIGHTGREEN,BG_LIGHTGREEN,BG_LIGHTGREEN,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY }
		};






		unsigned short word_color_temp[8][20] =
		{
			{ WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,	WORD_BLACK ,WORD_BLACK ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,	WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,	WORD_WHITE ,WORD_WHITE ,WORD_GREEN ,WORD_GREEN ,	WORD_GREEN ,WORD_GREEN ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,	WORD_WHITE ,WORD_WHITE ,WORD_GREEN ,WORD_GREEN ,	WORD_WHITE ,WORD_WHITE ,WORD_WHITE ,WORD_WHITE ,WORD_GREEN ,WORD_GREEN ,	WORD_GREEN ,WORD_GREEN ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,	WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_WHITE ,WORD_WHITE ,WORD_WHITE ,WORD_WHITE ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_GREEN ,WORD_GREEN ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_WHITE ,WORD_WHITE ,	WORD_WHITE ,WORD_WHITE ,WORD_WHITE ,WORD_WHITE ,	WORD_WHITE ,WORD_WHITE ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,		WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY },
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY,WORD_BLACK ,WORD_BLACK ,	WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,	WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY },
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_LIGHTGREY,		WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_LIGHTGREY,
			WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY }
		};





		for (int i = 0; i < 8; i++)
		{
			pic[i] = pic_temp[i];
			for (int j = 0; j < 20; j++)
			{
				background_color[i][j] = background_color_temp[i][j];
				word_color[i][j] = word_color_temp[i][j];
			}

		}
	}
	Icon_BlackSister()
	{
		Initialize();
	}

};