#pragma once
#include"Icons.h"

class Icon_IF : public Icons
{
public:
	void Initialize()
	{

		string pic_temp[8] = {
			"  ¡Z¢d¢e¢d¢b¡«¢@    ",
			"  ¢¨¢¨¢f¢f¢f¢©¢@¡«  ",
			"¢o¢«¢k¢i¢i¢i¢b¢©    ",
			"¢m  ¢k¡Z¢i¢i¢g¢l¡«  ",
			"¢o  ¢l| ¢i¢i¡þ¢k    ",
			"  ¢@¢o¢m¢h¢h¢n      ",
			"      ¢ª¢i¢b¢«      ",
			"        ¢h          "
		};

		unsigned short temp_bg[8][10]=

		{
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_BLACK ,BG_BLACK ,BG_BLACK ,BG_BLACK ,BG_BLACK ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_BLACK ,BG_LIGHTGREY ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_BLACK ,BG_LIGHTGREY ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_GREEN ,BG_WHITE ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_BLACK ,BG_LIGHTGREY ,BG_LIGHTGREEN ,BG_LIGHTGREEN ,BG_GREEN ,BG_GREEN ,BG_LIGHTGREEN ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_WHITE ,BG_LIGHTGREEN ,BG_GREEN ,BG_GREEN ,BG_WHITE ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREEN ,BG_LIGHTGREEN ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREEN ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY }
		};

		unsigned short background_color_temp[8][20];


		unsigned short temp_color[8][10] =
		{
			{ WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_WHITE ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_LIGHTGREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_GREEN ,WORD_LIGHTGREEN ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_WHITE ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREEN ,WORD_LIGHTGREEN ,WORD_LIGHTGREY ,WORD_LIGHTGREEN ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK }
		};


		unsigned short word_color_temp[8][20];



		for (int i = 0; i < 8; i++)
		{
			for (int j = 0; j < 20; j++)
			{
				background_color_temp[i][j] = temp_bg[i][j / 2];
				word_color_temp[i][j] = temp_color[i][j / 2];
			}
		}

		for (int i = 0; i < 8; i++)
		{
			pic[i] = pic_temp[i];
			for (int j = 0; j < 20; j++)
			{
				background_color[i][j] = background_color_temp[i][j];
				word_color[i][j] = word_color_temp[i][j];
			}

		}
	}
	Icon_IF()
	{
		Initialize();
	}

};