#pragma once
#include"Icons.h"

class Icon_Arforie : public Icons
{
public:
	void Initialize()
	{

		string pic_temp[8] = {
			"  ¤@¢d¢b      ¡«    ",
			"¢¨¢i¢b¢i¢h¢g¢e¢c¢@  ",
			"¢l    ¢k¢n¢j¢h¢ª¢©¡«",
			"¢ª    ¢l¢l¢j    ¢n  ",
			"¢@¢@  ¢n¢i        ¡«",
			"  ¢@¢@¢c¢n¢c¡Z      ",
			"  ¡þ¡«¢l¢«          ",
			"      ¢m            "

		};

		unsigned short temp_bg[8][10] =

		{
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_MAGENTA ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_RED ,BG_RED ,BG_LIGHTGREY ,BG_MAGENTA ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTRED ,BG_LIGHTRED ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTRED ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_MAGENTA ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_MAGENTA ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY }
		};

		unsigned short background_color_temp[8][20];


		unsigned short temp_color[8][10] =
		{
			{ WORD_BLACK ,WORD_MAGENTA ,WORD_MAGENTA ,WORD_MAGENTA ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_MAGENTA ,WORD_MAGENTA ,WORD_LIGHTGREY ,WORD_MAGENTA ,WORD_MAGENTA ,WORD_MAGENTA ,WORD_MAGENTA ,WORD_MAGENTA ,WORD_BLACK ,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_BLACK ,WORD_RED ,WORD_LIGHTGREY ,WORD_MAGENTA ,WORD_MAGENTA ,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_BLACK ,WORD_LIGHTRED ,WORD_GREEN ,WORD_GREEN ,WORD_BLACK ,WORD_BLACK },
			{ WORD_BLACK ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTRED ,WORD_GREEN ,WORD_GREEN ,WORD_LIGHTGREEN ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_LIGHTRED ,WORD_BLACK ,WORD_BLACK ,WORD_LIGHTGREEN ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_BLACK ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREEN ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK }
		};


		unsigned short word_color_temp[8][20];



		for (int i = 0; i < 8; i++)
		{
			for (int j = 0; j < 20; j++)
			{
				background_color_temp[i][j] = temp_bg[i][j / 2];
				word_color_temp[i][j] = temp_color[i][j / 2];
			}
		}

		for (int i = 0; i < 8; i++)
		{
			pic[i] = pic_temp[i];
			for (int j = 0; j < 20; j++)
			{
				background_color[i][j] = background_color_temp[i][j];
				word_color[i][j] = word_color_temp[i][j];
			}

		}
	}
	Icon_Arforie()
	{
		Initialize();
	}

}; 