#pragma once
#include"Icons.h"

class Icon_Uni : public Icons
{
public:
	void Initialize()
	{

		string pic_temp[8] = {
			"  ╴▃▄▃▃▁‵＼  ",
			"  ◢◢▇▆▆◣◣＼  ",
			"▉▉████▂▎◣  ",
			"▉▊█, ██▆▍‵  ",
			"  ▉▍◣█▉∕▎    ",
			"  ＼◥▏▇′▋      ",
			"    ‵◥█▂◤      ",
			"      ‵▇          "
		};
		unsigned short background_color_temp[8][20] =
		{
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_BLACK,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY },
			{ BG_BLACK,BG_BLACK,BG_RED,BG_RED,BG_RED,BG_RED,BG_RED,BG_RED,BG_RED,BG_RED,BG_RED,BG_RED,BG_RED,BG_RED,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_BLACK,BG_BLACK, BG_RED ,BG_RED ,BG_RED ,BG_RED ,BG_RED ,BG_RED ,BG_RED ,BG_RED ,BG_RED ,BG_RED ,BG_WHITE ,BG_WHITE ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY ,BG_LIGHTGREY, BG_RED ,BG_RED ,BG_LIGHTRED ,BG_LIGHTRED ,BG_RED ,BG_RED ,BG_RED ,BG_RED ,BG_LIGHTRED ,BG_LIGHTRED,BG_LIGHTRED ,BG_LIGHTRED ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY  },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTRED,BG_LIGHTRED,BG_RED,BG_RED,BG_LIGHTRED ,BG_LIGHTRED ,BG_WHITE ,BG_WHITE ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,	BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTRED,BG_LIGHTRED,	BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY },
			{ BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,	BG_LIGHTRED,BG_LIGHTRED,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY ,BG_LIGHTGREY }
		};






		unsigned short word_color_temp[8][20] =
		{
			{ WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK,WORD_BLACK },
			
			{ WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,	WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,	WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,	WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,	WORD_WHITE ,WORD_WHITE ,WORD_RED ,WORD_RED ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,	WORD_RED ,WORD_RED ,WORD_LIGHTRED ,WORD_LIGHTRED ,	WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,	WORD_RED ,WORD_RED ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
		
			{ WORD_BLACK ,WORD_BLACK ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,	WORD_RED ,WORD_RED ,WORD_LIGHTRED ,WORD_LIGHTRED ,	WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_RED ,WORD_LIGHTRED ,WORD_LIGHTRED ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK },
			
			{ WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_BLACK ,WORD_WHITE ,WORD_WHITE ,WORD_WHITE ,WORD_WHITE ,WORD_LIGHTRED ,WORD_LIGHTRED ,	WORD_RED ,WORD_RED ,WORD_LIGHTRED ,WORD_LIGHTRED ,WORD_LIGHTRED ,WORD_LIGHTRED ,		WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY },
		
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_BLACK ,WORD_BLACK ,WORD_LIGHTRED ,WORD_LIGHTRED ,	WORD_LIGHTRED ,WORD_LIGHTRED ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTRED ,WORD_LIGHTRED ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY },
			
			{ WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_BLACK,WORD_BLACK,		WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_LIGHTGREY,WORD_LIGHTGREY,
			WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY ,WORD_LIGHTGREY }
		};





		for (int i = 0; i < 8; i++)
		{
			pic[i] = pic_temp[i];
			for (int j = 0; j < 20; j++)
			{
				background_color[i][j] = background_color_temp[i][j];
				word_color[i][j] = word_color_temp[i][j];
			}

		}
	}
	Icon_Uni()
	{
		Initialize();
	}

};